[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["BASE_PATH=/ pnpm --filter @workspace/bio run build"]

[start]
cmd = "BASE_PATH=/ pnpm --filter @workspace/bio run serve"
